config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "static_pages#home"
  get '/404', to: 'errors#not_found'
  get  "/about", to: "static_pages#about"
  get  "/help", to: "static_pages#help"
  get  "/user-management", to: "static_pages#user_management"
  resources :help_sections, only: [:new, :create, :edit, :update, :destroy], :path => "documentation"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  devise_scope :user do
    delete "delete_avatar" => "registrations"
  end
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :support_issues, only: [:index, :show, :new, :create, :update], :path => "support" do
    resources :support_replies, only: [:create], :path => "reply"
    resources :support_comments, only: [:create], :path => "comment"
    resources :support_notes, only: [:create], :path => "note"
  end
  resources :users, only: [:index, :show, :new, :edit, :update, :destroy] do
    member do
      delete :delete_avatar
      resources :support_issues, only: [:index], :path => "support"
      get :following, :followers
    end
  end
  resources :site_settings, only: [:edit, :update], :path => "settings" do
    member do
      delete :delete_default_avatar
      delete :delete_logo
      delete :delete_favicon
      delete :delete_apple_touch_icon
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :tables, only: [:show, :create, :update]
end

app/models/support_issue.rb
class SupportIssue < ApplicationRecord
  include Support
  include SupportUserReplies

  has_many :support_replies, dependent: :destroy
  has_many :support_comments, dependent: :destroy
  has_many :support_notes, dependent: :destroy

  validates_length_of :summary, minimum: 3, maximum: 255, allow_blank: false

  def to_param
    self.display_name
  end

  def display_name
    "ISSUE-#{self.id}"
  end
end

app/controllers/support_issues_controller.rb
class SupportIssuesController < ApplicationController
  before_action :authenticate_user!
  before_action :users_allowed_to_contact
  before_action :is_admin, only: [:update]
  before_action :set_issue, only: %i[show update]
  before_action :correct_user_for_index, only: [:index]
  before_action :correct_user_for_show, only: [:show]

  def index
    require 'will_paginate/array'
    if params[:id]
      @user = User.find_by(username: params[:id])
      @support_issues = @user.support_issues.order(addressed: :asc, updated_at: :desc )
      @support_issues = @support_issues.paginate(page: params[:page], per_page: 5)
    else
      @support_issues = SupportIssue.all.order(addressed: :asc, updated_at: :desc )
      @support_issues = @support_issues.paginate(page: params[:page], per_page: 5)
    end
  end

  def show
    require 'will_paginate/array'
    @comments = @support_issue.support_comments
    @replies = @support_issue.support_replies
    if current_user.admin
      @notes = @support_issue.support_notes
      @all_comments = @comments + @replies + @notes
      @all_comments = @all_comments.sort_by(&:created_at)
    else
      @all_comments = @comments + @replies
      @all_comments = @all_comments.sort_by(&:created_at)
    end
    if current_user.id == @support_issue.user_id
      @support_comment = @support_issue.support_comments.build
    else
      @support_note = @support_issue.support_notes.build
      @support_reply = @support_issue.support_replies.build
    end
  end

  def new
    @support_issue = current_user.support_issues.build
  end

  def create
    @support_issue = current_user.support_issues.build(support_issue_create_params)
    respond_to do |format|
      if @support_issue.save
        @support_issue.update(user_id: current_user.id)
        @support_issue.update(user_email: current_user.email)
        @support_issue.update(status_log:
          'Issue Created at ' +
          @support_issue.created_at.strftime('%b %d, %Y %I:%M%p %Z') +
          ' by ' + current_user.username + ' (' +
          current_user.email + ")\n")
        if SiteSetting.email_admins_contact_form?
          AdminsMailer.support_issue_created(@support_issue, current_user).deliver_later
        end
        if SiteSetting.email_issue_status_to_users?
          UserMailer.support_issue_created(@support_issue).deliver_later
        end
        format.html { redirect_to help_url,
                                  notice: 'Support form successfully submitted.' }
        format.json { render :show, status: :created, location: @support_issue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @support_issue.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @support_issue.update(support_issue_update_params)
        if @support_issue.addressed == true
          update_log = @support_issue.status_log + 'Issue Resolved at ' + @support_issue.updated_at.strftime('%b %d, %Y %I:%M%p %Z') + ' by ' + current_user.username + ' (' + current_user.email + ")\n"
          @support_issue.update(status_log: update_log)
          if SiteSetting.email_admins_contact_form?
            AdminsMailer.support_issue_resolved(@support_issue, current_user).deliver_later
          end
          if SiteSetting.email_issue_status_to_users?
            UserMailer.support_issue_resolved(@support_issue).deliver_later
          end
        else
          update_log = @support_issue.status_log + 'Issue Reopened at ' + @support_issue.updated_at.strftime('%b %d, %Y %I:%M%p %Z') + ' by ' + current_user.username + ' (' + current_user.email + ")\n"
          @support_issue.update(status_log: update_log)
          if SiteSetting.email_admins_contact_form?
            AdminsMailer.support_issue_reopened(@support_issue, current_user).deliver_later
          end
          if SiteSetting.email_issue_status_to_users?
            UserMailer.support_issue_reopened(@support_issue).deliver_later
          end
        end
        format.html { redirect_to @support_issue,
                                  notice: 'Support issue status has been updated.' }
        format.json { render :show, status: :ok, location: @support_issue }
      else
        format.html { redirect_to @support_issue, status: :unprocessable_entity }
        format.json { render json: @support_issue.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_issue
    @support_issue = SupportIssue.find_by_id(params[:id].delete_prefix("ISSUE-"))
    render 'errors/not_found' unless @support_issue
  end

  # Only admins can view support issues show and index
  def is_admin
    redirect_to root_path unless current_user.admin?
  end

  def correct_user_for_index
    if params[:id]
      render 'errors/not_found' unless (params[:id] == current_user.username || current_user.admin?)
    else
      render 'errors/not_found' unless current_user.admin?
    end
  end

  def correct_user_for_show
    render 'errors/not_found' unless (@support_issue.user_id == current_user.id || current_user.admin?)
  end

  def users_allowed_to_contact
    render 'errors/not_found' unless SiteSetting.first.contact_form
  end

  # Only allow a list of trusted parameters through.
  def support_issue_create_params
    params.require(:support_issue).permit(:summary, :body, :rich_text_body)
  end

  def support_issue_update_params
    params.require(:support_issue).permit(:addressed)
  end
end

app/helpers/support_issues_helper.rb
module SupportIssuesHelper
end

app/views/support_issues/_status_form.html.haml
#status_form.mb-3.mt-3
  .btn-group{"aria-label" => "Support issue", :role => "group"}
    - if !support_issue.addressed
      = button_to "Resolve", support_issue_path(support_issue), params: { :support_issue => { :addressed => true } }, method: :patch, form: { data: { turbo_confirm: 'Are you sure you want to resolve this issue?' }}, class: "btn btn-sm btn-first" +  status_button_class
    - else
      = button_to "Reopen", support_issue_path(support_issue), params: { :support_issue => { :addressed => false } }, method: :patch, form: { data: { turbo_confirm: 'Are you sure you want to reopen this issue?' }}, class: "btn btn-sm btn-first" +  status_button_class
    - if !support_issue.addressed
      = link_to("Reply", support_issue_path(support_issue, :anchor => "reply"), class: "btn btn-sm" +  status_button_class)
    - else
      = link_to("Note", support_issue_path(support_issue, :anchor => "reply"), class: "btn btn-sm" +  status_button_class)

app/views/support_issues/_view_status_history.haml
.mb-3.mt-3
  = simple_format @support_issue.status_log

app/views/support_issues/index.html.haml
- provide(:title, 'Support Issues')
%h1 Support Issues
%table#support_issues{:class => "table table-hover mb-5#{table_class}"}
  %thead
    %tr
      %th.text-center{:scope => "col"} User
      %th.text-center{:scope => "col"} Status
      %th.text-center{:scope => "col"} Details
      %th.text-center{:scope => "col"} Reply
  %tbody
    - @support_issues.each do |support_issue|
      %tr{:id => "#{dom_id support_issue}"}
        %td.text-break{:style => "width: 25%"}
          %strong
            - if !support_issue.creator.nil?
              = link_to support_issue.creator_handle,               |
                user_path(support_issue.creator), class: link_class |
            - else
              [Deleted User Account]
          %br/
          = support_issue.user_email
          %br/
          %small
            Submitted #{resource_created(support_issue)}
        %td.text-center
          - if support_issue.addressed
            %span.badge.bg-light.text-dark RESOLVED
          - else
            %span.badge.bg-dark.bg-light OPEN
        %td.text-break
          = link_to support_issue, class: link_class do
            %strong>
              #{support_issue.display_name}
            \: #{support_issue.summary}
          %br/
          - if !support_issue.body.nil?
            = support_issue.body.truncate(300)
            - if support_issue.body.length > 300
              = link_to "See more", support_issue, class: link_class
          - else
            = truncate_actiontext_html(support_issue.rich_text_body.to_s, link_class: link_class, max_length: 300, read_more_path: support_issue_path(support_issue)).html_safe
        %td.text-center
          - if !support_issue.addressed
            = link_to("Reply", support_issue_path(support_issue, :anchor => "reply"), class: "btn btn-primary btn-sm")
          - else
            = link_to("Note", support_issue_path(support_issue, :anchor => "reply"), class: "btn btn-primary btn-sm")
= will_paginate @support_issues, list_classes: %w(pagination pagination-sm justify-content-center)

app/views/support_issues/new.html.haml
- provide(:title, 'Contact Us')
%h1 Contact Us
= form_with(model: @support_issue, method: :post) do |form|
  = render 'error_messages', object: @support_issue, object_name: 'this support issue'
  .mb-3
    = form.label :summary, style: "display: block", class: "form-label"
    = form.text_field :summary, class: "form-control form-control-sm" + input_class
  - if SiteSetting.rich_text_support_issues?
    #tables-data.mb-3{"data-controller" => "rich-text", "data-record-id" => "#{@support_issue.id}", "data-record-type" => "SupportIssue"}
      = form.label "Details", style: "display: block", class: "form-label"
      = form.rich_text_area :rich_text_body, class: "form-control"+ input_class
  - else
    .mb-3
      = form.label "Details", style: "display: block", class: "form-label"
      = form.text_area :body, class: "form-control form-control-sm"+ input_class
  %div
    = form.submit "Submit", class: "btn btn-primary btn-sm"

app/views/support_issues/show.html.haml
- provide(:title, 'Support Issue')
%h1
  #{@support_issue.display_name}
.mb-3{:id => "#{dom_id @support_issue}"}
  .mb-3
    - if current_user.admin
      = render 'status_form', support_issue: @support_issue
    %strong From:
    - if !@support_issue.creator.nil?
      = link_to (@support_issue.creator_handle),             |
        user_path(@support_issue.creator), class: link_class |
    - else
      [Deleted User Account]
    (#{@support_issue.user_email})
  .mb-3.text-break
    %strong Summary:
    = @support_issue.summary
  .mb-3
    %strong Submitted:
    = resource_created(@support_issue)
  .mb-3
    %strong Status:
    - if @support_issue.addressed
      %span.badge.bg-light.text-dark RESOLVED
    - else
      %span.badge.bg-dark.bg-light OPEN
  .mb-3.text-break
    - if !@support_issue.body.nil?
      = @support_issue.body
    - else
      = @support_issue.rich_text_body
  %hr/
  - if !@all_comments.empty?
    %table#all_comments{:class => "table table-hover mb-3#{table_class}"}
      %tbody
        - @all_comments.each do |comment|
          - if comment.is_a?(SupportReply)
            = render 'support_replies/support_reply', support_reply: comment
          - elsif comment.is_a?(SupportComment)
            = render 'support_comments/support_comment', support_comment: comment
          - elsif comment.is_a?(SupportNote)
            = render 'support_notes/support_note', support_note: comment
  #reply.mb-3
    - if @support_issue.user_id == current_user.id
      %ul#myTab.nav.nav-tabs{:role => "tablist"}
        %li.nav-item{:role => "presentation"}
          %button#home-tab{"aria-controls" => "home-tab-pane", "aria-selected" => "true", :class => "nav-link active#{link_class}", "data-bs-target" => "#home-tab-pane", "data-bs-toggle" => "tab", :role => "tab", :type => "button"}
            Reply to Admins
        - if current_user.admin
          %li.nav-item{:role => "presentation"}
            %button#contact-tab{"aria-controls" => "contact-tab-pane", "aria-selected" => "false", :class => "nav-link#{link_class}", "data-bs-target" => "#contact-tab-pane", "data-bs-toggle" => "tab", :role => "tab", :type => "button"}
              View Status History
      #myTabContent.tab-content
        #home-tab-pane.tab-pane.fade.show.active{"aria-labelledby" => "home-tab", :role => "tabpanel", :tabindex => "0"}
          = render 'support_comments/form', support_comment: [@support_issue, @support_comment]
        #contact-tab-pane.tab-pane.fade{"aria-labelledby" => "contact-tab", :role => "tabpanel", :tabindex => "0"}
          = render 'view_status_history', support_issue: @support_issue
    - else
      %ul#myTab.nav.nav-tabs{:role => "tablist"}
        - if !@support_issue.addressed && !@support_issue.creator.nil?
          %li.nav-item{:role => "presentation"}
            %button#home-tab{"aria-controls" => "home-tab-pane", "aria-selected" => "true", :class => "nav-link active#{link_class}", "data-bs-target" => "#home-tab-pane", "data-bs-toggle" => "tab", :role => "tab", :type => "button"}
              Reply to User
          %li.nav-item{:role => "presentation"}
            %button#profile-tab{"aria-controls" => "profile-tab-pane", "aria-selected" => "false", :class => "nav-link#{link_class}", "data-bs-target" => "#profile-tab-pane", "data-bs-toggle" => "tab", :role => "tab", :type => "button"}
              Make Internal Note
        - else
          %li.nav-item{:role => "presentation"}
            %button#profile-tab{"aria-controls" => "profile-tab-pane", "aria-selected" => "false", :class => "nav-link active#{link_class}", "data-bs-target" => "#profile-tab-pane", "data-bs-toggle" => "tab", :role => "tab", :type => "button"}
              Make Internal Note
        - if current_user.admin
          %li.nav-item{:role => "presentation"}
            %button#contact-tab{"aria-controls" => "contact-tab-pane", "aria-selected" => "false", :class => "nav-link#{link_class}", "data-bs-target" => "#contact-tab-pane", "data-bs-toggle" => "tab", :role => "tab", :type => "button"}
              View Status History
      #myTabContent.tab-content
        - if !@support_issue.addressed && !@support_issue.creator.nil?
          #home-tab-pane.tab-pane.fade.show.active{"aria-labelledby" => "home-tab", :role => "tabpanel", :tabindex => "0"}
            = render 'support_replies/form', support_reply: [@support_issue, @support_reply]
          #profile-tab-pane.tab-pane.fade{"aria-labelledby" => "profile-tab", :role => "tabpanel", :tabindex => "0"}
            = render 'support_notes/form', support_note: [@support_issue, @support_note]
        - else
          #profile-tab-pane.tab-pane.fade.show.active{"aria-labelledby" => "profile-tab", :role => "tabpanel", :tabindex => "0"}
            = render 'support_notes/form', support_note: [@support_issue, @support_note]
        - if current_user.admin
          #contact-tab-pane.tab-pane.fade{"aria-labelledby" => "contact-tab", :role => "tabpanel", :tabindex => "0"}
            = render 'view_status_history', support_issue: @support_issue