config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "static_pages#home"
  get '/404', to: 'errors#not_found'
  get  "/about", to: "static_pages#about"
  get  "/help", to: "static_pages#help"
  get  "/user-management", to: "static_pages#user_management"
  resources :help_sections, only: [:new, :create, :edit, :update, :destroy], :path => "documentation"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  devise_scope :user do
    delete "delete_avatar" => "registrations"
  end
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :support_issues, only: [:index, :show, :new, :create, :update], :path => "support" do
    resources :support_replies, only: [:create], :path => "reply"
    resources :support_comments, only: [:create], :path => "comment"
    resources :support_notes, only: [:create], :path => "note"
  end
  resources :users, only: [:index, :show, :new, :edit, :update, :destroy] do
    member do
      delete :delete_avatar
      resources :support_issues, only: [:index], :path => "support"
      get :following, :followers
    end
  end
  resources :site_settings, only: [:edit, :update], :path => "settings" do
    member do
      delete :delete_default_avatar
      delete :delete_logo
      delete :delete_favicon
      delete :delete_apple_touch_icon
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :tables, only: [:show, :create, :update]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:help, :user_management]
  before_action :admin_user, only: [:user_management]

  def home; end

  def about; end

  def help
    @help_sections = HelpSection.order('lower(title)').all
  end

  def user_management
    if params[:view_admins].present? && params[:view_admins] == '1'
      @users = User.admin_search(params[:search], admin: true, page: params[:page], per_page: 2)
    else
      @users = User.admin_search(params[:search], page: params[:page], per_page: 2)
    end
  end

  private

  def admin_user
    redirect_to root_path, alert: 'Not authorized.' unless current_user.admin?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.haml
- provide(:title, 'About')
%h1 About
%p Edit this static page in app/views/static_pages/about.html.erb

app/views/static_pages/help.html.haml
- provide(:title, 'Help')
%h1 Help
.row
  .col-md-3
    - if !@help_sections.empty? || SiteSetting.allow_users_to_contact_admins?
      %ul.list-group.list-group-flush.mb-3
        - @help_sections.each do |help_section|
          = link_to help_path(:anchor => 'help_section_' + help_section.id.to_s ), class: "text-break" do
            %li{:class => "list-group-item list-group-item-action#{list_group_item_class}"}
              = help_section.title
        - if SiteSetting.allow_users_to_contact_admins?
          = link_to help_path(:anchor => 'contact_admins') do
            %li{:class => "list-group-item list-group-item-action#{list_group_item_class}"}
              %i.bi.bi-envelope>
              Contact Site Admins
    - if current_user.admin
      .mb-5
        = link_to new_help_section_path, class: link_class do
          %i.bi.bi-plus>
          Add help section
  .col-md-9
    - @help_sections.each do |help_section|
      = render help_section
    - if SiteSetting.allow_users_to_contact_admins?
      #contact_admins.mb-5
        %h2 Contact Site Admins
        %p Not finding what you need?
        .mb-3
          = link_to "Get Support", new_support_issue_path, class: "btn btn-primary btn-sm"
    - if current_user.admin && !@help_sections.empty?
      .mb-3
        = link_to new_help_section_path, class: link_class do
          %i.bi.bi-plus>
          Add help section

app/views/static_pages/home.html.haml
%h1 Ruby on Rails Rails Base App
%p This application uses Devise for user registration and has an admin interface for managing users. Users can set a password or sign in through their google account after confirming their email. Users may select a username for public display and an avatar.
%p In the site settings, admins can decide if users are allowed to sign up for the application or if they need to be created through the admin interface only. Admins can select a default avatar image, logo, and site name from the site settings.
%p A basic support issue tracker can be enabled to allow users to submit feedback and issues to admins. Admins can reply, add internal notes, and resolve these issues.
%p Dark mode is available for users.
%p In the development environment, admins can login as other confirmed users.
%p
  %strong Source code:
  %a{:class => link_class, :href => "https://gitlab.com/endtoendpaper/devise-admin-oauth"} https://gitlab.com/endtoendpaper/devise-admin-oauth

app/views/static_pages/user_management.html.haml
- provide(:title, 'User Management')
%h1 User Management
.mb-4.mt-4
  = link_to 'New User', new_user_path, class: 'btn btn-primary btn-sm'
%div{"data-controller" => "toggle-admin-only-view"}
  .mb-3
    = form_tag(user_management_path, method: :get, class: 'row') do
      .input-group.mb-2.mt-2
        = text_field_tag(:search, params[:search], class: 'form-control form-control-sm custom-placeholder' + input_class, style: "max-width:250px;", placeholder: "Search by Email or Username")
        = hidden_field_tag :view_admins, "0", data: { "toggle-admin-only-view-target": "admins" }
        = button_tag nil, class: 'btn btn-primary btn-sm' do
          %i.bi.bi-search
          Search
        = link_to 'Clear', user_management_path, class: 'btn btn-secondary btn-sm'
  .form-check.form-switch.ms-2
    = form_tag(user_management_path, method: :get, data: { "toggle-admin-only-view-target": "submit" }) do
      = hidden_field_tag :search, "", data: { "toggle-admin-only-view-target": "query" }
      = check_box_tag :view_admins, 1, false, data: { "action": "click->toggle-admin-only-view#toggle", "toggle-admin-only-view-target": "toggle" }, "class": "form-check-input", "type": "checkbox", "role": "switch"
      %label.form-check-label{:for => "view_admins"} Admin users
- if @users
  - @users.each do |user|
    .mb-5
      = render 'users/user', user: user
  = will_paginate @users, list_classes: %w(pagination pagination-sm justify-content-center)