config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "static_pages#home"
  get '/404', to: 'errors#not_found'
  get  "/about", to: "static_pages#about"
  get  "/help", to: "static_pages#help"
  get  "/user-management", to: "static_pages#user_management"
  resources :help_sections, only: [:new, :create, :edit, :update, :destroy], :path => "documentation"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  devise_scope :user do
    delete "delete_avatar" => "registrations"
  end
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :support_issues, only: [:index, :show, :new, :create, :update], :path => "support" do
    resources :support_replies, only: [:create], :path => "reply"
    resources :support_comments, only: [:create], :path => "comment"
    resources :support_notes, only: [:create], :path => "note"
  end
  resources :users, only: [:index, :show, :new, :edit, :update, :destroy] do
    member do
      delete :delete_avatar
      resources :support_issues, only: [:index], :path => "support"
      get :following, :followers
    end
  end
  resources :site_settings, only: [:edit, :update], :path => "settings" do
    member do
      delete :delete_default_avatar
      delete :delete_logo
      delete :delete_favicon
      delete :delete_apple_touch_icon
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :tables, only: [:show, :create, :update]
end

app/models/user.rb
require 'elasticsearch/model'

class User < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  attr_writer :login

  devise :database_authenticatable, :registerable, :trackable,
         :confirmable, :lockable, :timeoutable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  if Rails.env.development?
    devise :masqueradable
  end

  has_one_attached :avatar do |attachable|
    attachable.variant :tiny, resize_to_limit: [15, 15]
    attachable.variant :thumb, resize_to_limit: [100, 100]
    attachable.variant :medium, resize_to_limit: [200, 200]
  end
  has_many :active_relationships, class_name:  "Relationship",
            foreign_key: "follower_id",
            dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
            foreign_key: "followed_id",
            dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :support_issues, dependent: :nullify
  has_many :support_replies, dependent: :nullify
  has_many :support_comments, dependent: :nullify
  has_many :support_notes, dependent: :nullify

  VALID_EMAIL_REGEX = /\A[a-z\d\-_]*\z/i
  validates :username, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX, message: 'can only contain letters, numbers, dashes, or underscores' },
                    uniqueness: { case_sensitive: false }
  validates :avatar, blob: { content_type: :image, size_range: 1..(5.megabytes) }

  default_scope { order('lower(username)') }
  scope :ordered_by_id, -> { reorder(id: :asc) }
  scope :admins, -> { where(admin: true) }

  index_name "#{Rails.env}_users"

  settings do
    mappings dynamic: false do
      indexes :username, type: :text, analyzer: 'english'
      indexes :email, type: :keyword
      indexes :admin, type: :boolean
    end
  end

  def as_indexed_json(options = {})
    as_json(only: [:username, :email, :admin])
  end

  def to_param
    self.username_was
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Create users if they don't exist
    if SiteSetting.allow_users_to_join? && !user
      email_username = data['email'].split("@").first
      email_username = email_username.gsub!(/\W/, '') if email_username.gsub!(/\W/, '').present?
      new_username = email_username
      inc = 1
      while User.where("lower(username) = ?", new_username.downcase).count > 0
        new_username = email_username + inc.to_s
        inc = inc + 1
      end
      user = User.new(username: new_username,
                         email: data['email'],
                         password: Devise.friendly_token[0, 20])
      user.skip_confirmation!
      user.save
    elsif user && !user.confirmed?
      user.skip_confirmation!
      user.save
    end

    user
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    if (login.include?('@'))
      where(conditions.to_h).where(["lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_h).where(["username = :value", { :value => login }]).first
    end
  end

  def self.search(query, page: 1, per_page: 50)
    page = page.to_i <= 0 ? 1 : page.to_i

    if query.present?
      search_body = {
        query: {
          multi_match: {
            query: query,
            fields: ['username'],
            fuzziness: "AUTO"
          }
        }
      }

      if per_page
        search_body.merge!({
          from: (page.to_i - 1) * per_page.to_i,
          size: per_page.to_i
        })
      end

      search_response = User.__elasticsearch__.search(search_body)

      WillPaginate::Collection.create(page.to_i, per_page.to_i, search_response.response['hits']['total']['value']) do |pager|
        pager.replace(search_response.records.to_a)
      end
    else
      all.order('username ASC').paginate(page: page, per_page: per_page)
    end
  end

  def self.admin_search(query, admin: false, page: 1, per_page: 50)
    page = page.to_i <= 0 ? 1 : page.to_i

    if query.present?
      search_body = {
        query: {
          bool: {
            must: [
              {
                multi_match: {
                  query: query,
                  fields: ['username^2', 'email'],
                  "fuzziness": "AUTO"
                }
              }
            ]
          }
        }
      }

      if admin
        search_body[:query][:bool][:filter] = [
          { term: { admin: true } }
        ]
      end

      if per_page
        search_body.merge!({
          from: (page.to_i - 1) * per_page.to_i,
          size: per_page.to_i
        })
      end

      search_response = User.__elasticsearch__.search(search_body)

      WillPaginate::Collection.create(page.to_i, per_page.to_i, search_response.response['hits']['total']['value']) do |pager|
        pager.replace(search_response.records.to_a)
      end
    elsif admin
      admins.order('username ASC').paginate(page: page, per_page: per_page)
    else
      all.order('username ASC').paginate(page: page, per_page: per_page)
    end
  end

  # Follows a user.
  def follow(other_user)
    following << other_user unless self == other_user || !SiteSetting.follow_users? || self.following?(other_user)
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user) if self.following?(other_user) unless !SiteSetting.follow_users?
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  def handle
    '@' + username
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user and @user.persisted? and !params.empty?
      @user.remember_me = true if devise_mapping.registerable? and @user.confirmed?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success',
                       kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    elsif !SiteSetting.allow_users_to_join?
      session['devise.google_data'] = request.env['omniauth.auth']
                                      .except('extra')
      redirect_to new_user_session_path unless current_user
    else
      session['devise.google_data'] = request.env['omniauth.auth']
                                      .except('extra')
      if !current_user
        redirect_to new_user_registration_url,
                  alert: @user.errors.full_messages.join("\n")
      end
    end
  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy delete_avatar followers following]
  before_action :authenticate_user!, except: [:show, :index, :following, :followers]
  before_action :follow_enabled, only: [:following, :followers]
  before_action :hide_followers, only: [:following, :followers]
  before_action :admin_user, except: [:show, :index, :following, :followers]

  # GET /users or /users.json
  def index
    @users = User.search(params[:search], page: params[:page], per_page: 5)
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update_without_password(user_params)
        format.html { redirect_to user_path(@user),
                      notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: root_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path,
                                notice: 'User was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def delete_avatar
    @user.avatar.purge if @user.avatar.attached?
    respond_to do |format|
      format.html { redirect_to edit_user_path(@user) }
      format.turbo_stream
    end
  end

  def following
    @title = "Following"
    @users = @user.following.paginate(page: params[:page], per_page: 5)
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    if current_user && current_user.admin
      @users = @user.followers.paginate(page: params[:page], per_page: 5)
    else
      @users = @user.followers.where(hide_relationships: false).paginate(page: params[:page], per_page: 5)
    end
    render 'show_follow'
  end

  private

  def follow_enabled
    render 'errors/not_found' unless SiteSetting.first.follow_users
  end

  def hide_followers
    if @user.hide_relationships && (!current_user || (!current_user.admin && current_user.id != @user.id))
      render 'errors/not_found'
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user =User.find_by(username: params[:id])
    render 'errors/not_found' unless @user
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:avatar, :password, :password_confirmation,
                                 :email, :username, :admin, :darkmode,
                                 :time_zone, :hide_relationships)
  end

  def admin_user
    redirect_to root_path, alert: 'Not authorized.' unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_left_col_classes
    if action_name == 'following' || action_name == 'followers'
      " col-xl-3 "
    else
      " col-sm-6 col-md-4 col-lg-3 col-xl-3 col-xxl-2 mt-3 "
    end
  end

  def user_right_col_classes
    if action_name == 'following' || action_name == 'followers'
      " col-xl-9 "
    else
      " col-sm-6 col-md-8 col-lg-9 col-xl-9 col-xxl-10 "
    end
  end

  def can_view_follower_stats(user)
    !user.hide_relationships || (current_user && (current_user.admin || current_user.id == user.id))
  end
end

app/views/users/_admin_fields.html.haml
- if current_user && current_user.admin? && (action_name == 'user_management' || action_name == 'show')
  %hr
  - if @user.admin?
    %strong
      %span{:style => "color: red"} Admin
    %br
  %strong Email:
  = @user.email
  %br
  %strong Darkmode:
  = @user.darkmode
  %br
  %strong Hide Follow Relationships:
  = @user.hide_relationships
  %br
  %strong Timezone:
  = @user.time_zone
  %br
  %br
  %strong Sign in count:
  = @user.sign_in_count
  %br
  %strong Current sign in:
  = pretty_time(@user.current_sign_in_at)
  %br
  %strong Current sign in IP:
  = @user.current_sign_in_ip
  %br
  %strong Last sign in:
  = pretty_time(@user.last_sign_in_at)
  %br
  %strong Last sign in IP:
  = @user.last_sign_in_ip
  %br
  %br
  - if !@user.confirmed?
    %span{:style => "color: red"}
      %strong unconfirmed
    %br
  %strong Confirmation sent at:
  = pretty_time(@user.confirmation_sent_at)
  %br
  %strong Confirmed at:
  = pretty_time(@user.confirmed_at)
  %br
  %strong Unconfirmed email:
  = @user.unconfirmed_email
  %br
  %br
  %strong Failed login attemps:
  = @user.failed_attempts
  %br
  %strong Unlocked at:
  = @user.locked_at
  %br
  - if current_user.id != @user.id
    %br
    = link_to edit_user_path(@user), class: link_class do
      %i.bi.bi-pencil-fill
      Edit user

app/views/users/_avatar_and_username.html.haml
- if action_name == 'show'
  - if @user.avatar.attached?
    = image_tag(@user.avatar.variant(:medium))
    %br/
  - elsif SiteSetting.default_avatar.attached?
    = image_tag(default_avatar_path(:medium))
    %br/
  %h5= @user.handle
- else
  - if @user.avatar.attached?
    = link_to(image_tag(@user.avatar.variant(:medium)), user_path(@user))
    %br/
  - elsif SiteSetting.default_avatar.attached?
    = link_to(image_tag(default_avatar_path(:medium)), user_path(@user))
    %br/
  %h5= link_to @user.handle, user_path(@user), class: link_class

app/views/users/_avatar_display.html.haml
%span#avatar_display
  - if @user.avatar.attached?
    = image_tag(@user.avatar.variant(:thumb))
    %br/
    %br/
    = link_to 'Remove avatar', delete_avatar_user_path(@user), class: link_class, data: { "turbo-method": :delete, turbo_confirm: 'Are you sure?' }
    or set a new one:
  = " - Not set" if !@user.avatar.attached?
  %br/

app/views/users/_follow.html.haml
= form_with(model: current_user.active_relationships.build) do |f|
  %div= hidden_field_tag :followed_id, @user.id
  = f.button nil, class: "btn btn-sm mt-2" + follow_button_class  do
    %i.bi.bi-person-plus-fill
    Follow

app/views/users/_follow_form.html.haml
- unless current_user.id == @user.id || action_name == 'user_management'
  %div{:id => "follow_form_user_#{@user.id}"}
    - if current_user.following?(@user)
      = render 'users/unfollow'
    - else
      = render 'users/follow'

app/views/users/_followers.html.haml
- if SiteSetting.follow_users?
  - if can_view_follower_stats(@user)
    .follower-stats
      %a{:class => "me-1 #{link_class}", :href => "#{following_user_path(@user)}"}
        %strong.stat{:id => "following_#{@user.id}"}
          = @user.following.count
        following
      %a{:class => link_class, :href => "#{followers_user_path(@user)}"}
        %strong.stat{:id => "followers_#{@user.id}"}
          = @user.followers.count
        followers
  - if current_user
    = render 'users/follow_form'

app/views/users/_masquerade.html.haml
- if Rails.env.development? && user_signed_in? && current_user.admin? && @user.confirmed?
  = link_to "Login As", masquerade_path(@user), class: "btn btn-sm mt-2" + masquerade_button_class

app/views/users/_unfollow.html.haml
= form_with(model: current_user.active_relationships.find_by(followed: @user), |
  html: { method: :delete }) do |f|                                            |
  = f.button nil, class: "btn btn-sm mt-2" + unfollow_button_class do
    %i.bi.bi-person-x-fill
    Unfollow

app/views/users/_user.html.haml
- @user = user
%div{:id => "#{dom_id user}"}
  .row
    %div{:class => "#{user_left_col_classes} mb-3"}
      = render 'users/avatar_and_username'
      = render 'users/followers'
      = render 'users/masquerade'
    %div{:class => "#{user_right_col_classes} mb-3"}
  - if current_user and current_user.id == user.id
    = link_to edit_user_registration_path, class: link_class do
      %i.bi.bi-pencil-fill
      Edit your profile
  = render 'users/admin_fields'

app/views/users/delete_avatar.turbo_stream.haml
= turbo_stream.update "avatar_display" do
  = render 'avatar_display'

app/views/users/edit.html.haml
- provide(:title, 'Edit ' + @user.username)
%h1
  Edit
  - if @user.admin?
    %span{:style => "color: red"} Admin
  - else
    User
  = @user.handle
.row
  .col-md-3
    %ul.list-group.list-group-flush.mb-3
      - if current_user.admin?
        = link_to edit_user_path(@user, :anchor => 'roles'), class: "text-break" do
          %li{:class => "list-group-item list-group-item-action#{list_group_item_class}"}
            Roles
      = link_to edit_user_path(@user, :anchor => 'profile'), class: "text-break" do
        %li{:class => "list-group-item list-group-item-action#{list_group_item_class}"}
          Profile
      = link_to edit_user_path(@user, :anchor => 'preferences'), class: "text-break" do
        %li{:class => "list-group-item list-group-item-action#{list_group_item_class}"}
          Preferences
      = link_to edit_user_path(@user, :anchor => 'cancel'), class: "text-break" do
        %li{:class => "list-group-item list-group-item-action#{list_group_item_class}"}
          Cancel Account
  .col-md-9
    = form_for @user, html: { multipart: true } do |f|
      = render 'error_messages', object: @user, object_name: 'this user'
      - if current_user.admin?
        #roles
          %h2 Roles
          .mb-5
            = f.check_box :admin, class: "form-check-input"
            = f.label :admin, class: "form-check-label"
      #profile
        %h2 Profile
        .mb-3
          = f.label :username, class: "form-label"
          %br/
          = f.text_field :username, autofocus: true, autocomplete: "username", class: "form-control form-control-sm" + input_class
          %div{:class => "form-text#{light_text_class}"} Only letters, numbers, dashes, and underscores.
        .mb-3
          = f.label :email, class: "form-label"
          %br/
          = f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control form-control-sm"
          %div{:class => "form-text#{light_text_class}"} If updated, a message with a confirmation link will be sent to user's new email address.
        - if !@user.confirmed?
          .mb-3
            %div
              Currently waiting
              %strong
                %span{:style => "color: red"} confirmation
              for: #{@user.email}
        - if @user.unconfirmed_email
          .mb-3
            %div
              Currently waiting
              %strong
                %span{:style => "color: red"} confirmation
              for: #{@user.unconfirmed_email}
        .mt-5.mb-5
          = f.label "Avatar", class: "form-label"
          = render 'avatar_display'
          = f.file_field :avatar, class: "form-control form-control-sm" + input_class, accept: 'image/png,image/jpg,image/jpeg'
      #preferences
        %h2 Preferences
        .mb-3
          = f.check_box :darkmode, class: "form-check-input"
          = f.label :darkmode, class: "form-check-label"
        - if SiteSetting.follow_users?
          .mb-3
            = f.check_box :hide_relationships, class: "form-check-input"
            = f.label :hide_relationships, "Hide Follow Relationships", class: "form-check-label"
            %div{:class => "form-text#{light_text_class}"}
              If this is checked, then only you will see your following/follower
              statistics and you will not display on other users’ follower lists.
        .mb-5
          = f.label 'Timezone', class: "form-label"
          = f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, {}, {class: "form-select form-select-sm" + input_class}
      .actions.mb-5
        = f.submit "Update", class: "btn btn-primary btn-sm"
    #cancel
      %h2 Cancel Account
      %p This action cannot be undone.
      .mb-3
        = button_to "Delete User", @user, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' }}, class: "btn btn-danger btn-sm"

app/views/users/index.html.haml
- provide(:title, 'Users')
%h1 Users
.mb-3
  = form_tag(users_path, method: :get, class: 'row') do
    .input-group.mb-2.mt-2
      = text_field_tag(:search, params[:search], class: 'form-control form-control-sm custom-placeholder' + input_class, style: "max-width:250px;", placeholder: "Search by Username")
      = button_tag nil, class: 'btn btn-primary btn-sm' do
        %i.bi.bi-search
        Search
      = link_to 'Clear', users_path, class: 'btn btn-secondary btn-sm'
- if @users
  - @users.each do |user|
    .mb-5
      = render user
  = will_paginate @users, list_classes: %w(pagination pagination-sm justify-content-center)

app/views/users/new.html.haml
- provide(:title, 'New User')
%h1 New User
= form_for @user, html: { multipart: true } do |f|
  .mb-3
    = f.label :email, class: "form-label"
    %br/
    = f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control form-control-sm" + input_class
  .mb-3
    = f.label :username, class: "form-label"
    %br/
    = f.text_field :username, autofocus: true, autocomplete: "username", class: "form-control form-control-sm" + input_class
    %div{:class => "form-text#{light_text_class}"} Only letters, numbers, dashes, and underscores.
  - if user_signed_in? and current_user.admin?
    .mb-3
      = f.check_box :admin, class: "form-check-input"
      = f.label :admin, class: "form-check-label"
  .mb-3
    = f.label :password, class: "form-label"
    .input-group.input-group-sm{"data-controller" => "password-visibility"}
      = f.password_field :password, autocomplete: "new-password", class: "form-control form-control-sm" + input_class, "data-password-visibility-target": "input"
      %button.input-group-text{"data-action" => "password-visibility#toggle", :type => "button"}
        %span{"data-password-visibility-target" => "icon"}
          %i.bi.bi-eye
        %span.hidden{"data-password-visibility-target" => "icon"}
          %i.bi.bi-eye-slash
    - if @minimum_password_length
      %div{:class => "form-text#{light_text_class}"}
        = @minimum_password_length
        characters minimum
  .mb-3
    = f.label :password_confirmation, class: "form-label"
    %br/
    .input-group.input-group-sm{"data-controller" => "password-visibility"}
      = f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control form-control-sm" + input_class, "data-password-visibility-target": "input"
      %button.input-group-text{"data-action" => "password-visibility#toggle", :type => "button"}
        %span{"data-password-visibility-target" => "icon"}
          %i.bi.bi-eye
        %span.hidden{"data-password-visibility-target" => "icon"}
          %i.bi.bi-eye-slash
  %div
    = f.submit "Create User", class: "btn btn-primary btn-sm"

app/views/users/show_follow.html.haml
- provide(:title, @title)
%h1= @title
- if @users
  .row
    .col-sm-6.col-md-4.col-lg-3.col-xl-3.col-xxl-2.mt-1.mb-5
      = render 'users/avatar_and_username'
      = render 'users/followers'
      - if @users.any?
        .mt-3
          - @users.each do |user|
            - if user.avatar.attached?
              = link_to(image_tag(user.avatar.variant(:tiny)), user_path(user), class: "float-start me-1")
            - elsif SiteSetting.default_avatar.attached?
              = link_to(image_tag(default_avatar_path(:tiny)), user_path(user), class: "float-start me-1")
    .col-sm-6.col-md-8.col-lg-9.col-xl-9.col-xxl-10
      - @users.each do |user|
        #test.mb-3
          = render user
      = will_paginate @users, list_classes: %w(pagination pagination-sm justify-content-center)