config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "static_pages#home"
  get '/404', to: 'errors#not_found'
  get  "/about", to: "static_pages#about"
  get  "/help", to: "static_pages#help"
  get  "/user-management", to: "static_pages#user_management"
  resources :help_sections, only: [:new, :create, :edit, :update, :destroy], :path => "documentation"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  devise_scope :user do
    delete "delete_avatar" => "registrations"
  end
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :support_issues, only: [:index, :show, :new, :create, :update], :path => "support" do
    resources :support_replies, only: [:create], :path => "reply"
    resources :support_comments, only: [:create], :path => "comment"
    resources :support_notes, only: [:create], :path => "note"
  end
  resources :users, only: [:index, :show, :new, :edit, :update, :destroy] do
    member do
      delete :delete_avatar
      resources :support_issues, only: [:index], :path => "support"
      get :following, :followers
    end
  end
  resources :site_settings, only: [:edit, :update], :path => "settings" do
    member do
      delete :delete_default_avatar
      delete :delete_logo
      delete :delete_favicon
      delete :delete_apple_touch_icon
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :tables, only: [:show, :create, :update]
end

app/models/help_section.rb
class HelpSection < ApplicationRecord
  include EditNotice
  include RichTextExtensions

  has_rich_text :content

  validates :title, presence: true, length: { maximum: 100 }
  validates_presence_of :content

  default_scope { order('lower(help_sections.title)') }

  def has_edit_privileges user
    user && user.admin
  end
end

app/controllers/help_sections_controller.rb
class HelpSectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin
  before_action :set_help_section, only: %i[edit update destroy]

  def new
    @help_section = HelpSection.new
  end

  def create
    @help_section = HelpSection.new(help_section_params)

    respond_to do |format|
      if @help_section.save
        format.html { redirect_to help_url,
                                  notice: 'Help section was successfully created.' }
                                  format.json { head :no_content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @help_section.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @help_section.update(help_section_params)
        format.html { redirect_to help_url,
                                  notice: 'Help section was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @help_section.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @help_section.destroy

    respond_to do |format|
      format.html { redirect_to help_url,
                                notice: 'Help section was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def is_admin
    redirect_to root_path, alert: 'Not authorized.' unless current_user.admin?
  end

  def set_help_section
    @help_section = HelpSection.find(params[:id])
  end

  def help_section_params
    params.require(:help_section).permit(:title, :content)
  end
end

app/helpers/help_sections_helper.rb
module HelpSectionsHelper
end

app/views/help_sections/_form.html.haml
= form_with(model: help_section) do |form|
  = render 'error_messages', object: help_section, object_name: 'this help section'
  .mb-3
    = form.label :title, style: "display: block", class: "form-label"
    = form.text_field :title, class: "form-control form-control-sm" + input_class
  #tables-data.mb-3{"data-controller" => "rich-text", "data-record-id" => "#{help_section.id}", "data-record-type" => "HelpSection"}
    = form.label :content, style: "display: block", class: "form-label"
    = form.rich_text_area :content, class: "form-control" + input_class
  %div
    = form.submit "Submit", class: "btn btn-primary btn-sm", id: "edit-btn"

app/views/help_sections/_help_section.html.haml
.mb-5{:id => "#{dom_id help_section}"}
  %h2= help_section.title
  = help_section.content
  - if current_user.admin
    .mt-3
      %small
        = link_to edit_help_section_path(help_section), class: link_class do
          %i.bi.bi-pencil-fill>
          Edit
      .float-end
        %small
          Updated #{resource_updated(help_section)}

app/views/help_sections/edit.html.haml
- provide(:title, 'Edit Help Section')
%h1 Edit Help Section
%span#edit-notice
  = turbo_stream_from @help_section, "edit_notice"
= render "form", help_section: @help_section
%br/
.mb-3
  = button_to "Delete Help Section", @help_section, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' }}, class: "btn btn-danger btn-sm"

app/views/help_sections/new.html.haml
- provide(:title, 'New Help Section')
%h1 New Help Section
= render "form", help_section: @help_section